# Generated by Django 5.1.6 on 2025-03-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailtemplates', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.client'),
        ),
    ]
