# Generated by Django 5.1.6 on 2025-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailtemplates', '0003_emailtemplate_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
    ]
